
server:
  shutdown: graceful

management:
  server.port: 8089
  health:
    linvessstate.enabled: true
    readinessstate.enable: true
  endpoint.health.probes.enabled: true

spring:
  messages:
    basename: messages
  jpa:
    generate-ddl: false
    show-sql: false
